apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: '{{ .Values.CanaryReplicaCount }}'
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 'masturhh/simplewebapp:{{ .values.image.tag }}'
        ports:
        - containerPort: 3000 