apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend_v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend_v2
        image: theoafactor/simplewebapp:v2
        ports:
        - containerPort: 3000